main: fr.crabii.homes.Main
name: Homes
version: 1.3
author: Crabii
api-version: 1.20

commands:
  sethome:
    description: Permet de créer un home
    permission: homes.sethome
  delhome:
    description: Permet de supprimer un home
    permission: homes.delhome
  home:
    description: Permet de se téléporter à un home
    permission: homes.home
  gethome:
    description: Permet de récupérer la liste des homes d'un joueur
    permission: homes.gethome
  gohome:
    description: Permet de ce teleporter au home d'un autre joueur
    permission: homes.gohome
  homegui:
    description: GUI qui affiche la liste des homes
    permission: homes.homegui